"use client"
import React from 'react'

export default function aboutUs() {
    return (
        <>
            <section class="about-us py-3 py-md-5 px-md-3"><div class="container"><div class="row align-items-center justify-content-center"><div class="col-md-6"><div class="about position-relative"><div class="section-header"><div class="section-tag">About Us</div><h1 class="section-title mb-3">Shaping Young Minds for the Future</h1></div><!-- <video width="550" autoplay="" muted="" loop=""><source src="https://resources.edunexttechnologies.com/web-data/gdg-roorkee/img/about-video.mp4" type="video/mp4" /> Your browser does not support the video tag. </video> --><!-- <video width="550" autoplay="" muted="" loop=""><source src="https://resources.edunexttechnologies.com/web-data/gdg-roorkee/video/about-latest-video.mp4" type="video/mp4" /> Your browser does not support the video tag. </video> --><video width="550" autoplay="" muted="" loop=""><source src="https://resources.edunexttechnologies.com/web-data/gdg-roorkee/video/about-video-img.mp4" type="video/mp4" /> Your browser does not support the video tag. </video><img src="https://resources.edunexttechnologies.com/web-data/gdg-roorkee/img/about-bird.svg" class="about-bird d-lg-inline d-none img-fluid" alt="Best School in Roorkee"/></div></div></div><div class="row align-items-center justify-content-center"><div class="col-md-10"><p class="fw-medium mt-3 mt-lg-0 text-center text-color">Education is the foundation of a brighter future, and at GD Goenka School Roorkee, we offer an unparalleled platform for your child’s growth. With world-class facilities, a value-driven curriculum, and experienced educators, we aim to empower students to achieve their fullest potential. Our motto, “Higher, Stronger, Brighter,” reflects our belief in excellence at every level.</p><div class="d-flex justify-content-center"><a href="about-school" class="btn btn-gold"><span>Know More</span></a></div></div></div></div></section>
        </>
    )
}
